parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: latest
  project: tsconfig.json

env:
  browser: true

extends:
  - airbnb-base
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - next
  - prettier

rules:
  no-plusplus: [ "error", { "allowForLoopAfterthoughts": true } ]
  no-console: [ "error", { allow: [ "error" ] } ]
  import/no-extraneous-dependencies: off
